name: Deploy AWS Lambda Code
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request'
      steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Run tests and check coverage
        run: |
          python3 -m coverage run tests/test_CreateProject.py
          coverage report
          
