name: Deploy AWS Lambda Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # trigger manually

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Install coverage
      run: |
        python -m pip install --upgrade pip
        pip install coverage
      
    - name: Run tests
      run: |
        python3 CreateProjectTests.py     
        coverage run CreateProjectTests.py
        coverage report
