name: Deploy AWS Lambda Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # trigger manually

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1

    steps:
    - name: checkout
      uses: actions/checkout@v2
      

    - name: Install coverage
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Run tests
      run: |
        python3 -m unittest tests/test_CreateProject.py

    - name: Coverage comment
      id: coverage_comment
      uses: ewjoachim/python-coverage-comment-action@v2
      with:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Store Pull Request comment to be posted
      uses: actions/upload-artifact@v2
      if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        name: python-coverage-comment-action
        path: python-coverage-comment-action.txt
